# Generated by Django 5.0.3 on 2024-03-25 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='job_title',
            new_name='designation',
        ),
    ]
