# Generated by Django 5.0.3 on 2024-03-25 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_job_title_employee_designation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='assessments',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.assessment'),
        ),
    ]
