# Generated by Django 5.0.3 on 2024-03-25 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_course_assessments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='assessments',
        ),
        migrations.AddField(
            model_name='assessment',
            name='course',
            field=models.ManyToManyField(to='api.course'),
        ),
    ]
