# Generated by Django 5.0.3 on 2024-03-25 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_course_number_of_students_course_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='date_of_hire',
            field=models.DateField(blank=True, null=True),
        ),
    ]
