# Generated by Django 5.0.3 on 2024-03-28 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_course_category_video_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='video',
            field=models.ManyToManyField(blank=True, null=True, to='api.video'),
        ),
    ]
