# Generated by Django 5.0.3 on 2024-03-28 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_course_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
