# Generated by Django 5.0.3 on 2024-03-29 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_assessmentquestion_assessment_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentquestion',
            name='answer_type',
            field=models.CharField(default='text', max_length=100),
            preserve_default=False,
        ),
    ]
