# Generated by Django 5.0.3 on 2024-03-29 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_assessmentquestion_answer_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment',
            name='questions',
        ),
        migrations.AddField(
            model_name='assessment',
            name='questions',
            field=models.ManyToManyField(blank=True, null=True, to='api.assessmentquestion'),
        ),
    ]
